name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    steps:
    - prepare-deps:
      uses: ./.github/workflows/rust-base.yml
      with:
        build-binary: true
    - name: Run tests
      run: cargo test --all

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build
#       run: docker build . --tag=qdrant
