name: Formatter and linter

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Prepare environment
        uses: ./.github/workflows/rust-base.yml
        with:
          build-binary: false
          use-nightly: true
      - name: Check code formatting
        run: cargo +nightly fmt --all -- --check
      - name: Check cargo clippy warnings
        run: cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings
