name: Storage compatibility tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare-deps:
    uses: ./.github/workflows/rust-base.yml
    with:
      build-binary: false
      use-nightly: true
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run storage compatibility test
        run: ./tests/storage-compat/storage-compatibility.sh
        shell: bash
