name: Storage compatibility tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - prepare-deps:
        uses: ./.github/workflows/rust-base.yml
      - name: Run storage compatibility test
        run: ./tests/storage-compat/storage-compatibility.sh
        shell: bash
